{
    "data": {
        "name": "ACC-SINV-RET-2024-00001", #자동으로 생성되는듯?
        "owner": "Administrator", #로그인 하면 이 이름은 full_name: "Administrator"  이런 식으로 반환됨.
        "creation": "2024-01-23 06:39:11.460831",
        "modified": "2024-01-23 06:39:11.460831",
        "modified_by": "Administrator",
        "docstatus": 0,
        "idx": 0,
        "title": "Seungmin Lee", #유저 이름과 같음
        "naming_series": "ACC-SINV-RET-.YYYY.-", # Series(필수)
        "customer": "Seungmin Lee",
        "customer_name": "Seungmin Lee",
        "company": "testCompany",
        "posting_date": "2024-01-23", #(필수)자동입력
        "posting_time": "6:39:11.936432",
        "set_posting_time": 0,
        "due_date": "2024-01-23", #Payment due date(필수)
        "is_pos": 0,
        "is_consolidated": 0,
        "is_return": 0,
        "update_billed_amount_in_sales_order": 0,
        "update_billed_amount_in_delivery_note": 1,
        "is_debit_note": 0,
        "currency": "KRW", #(필수)
        "conversion_rate": 1.0,
        "selling_price_list": "Standard Selling", #필수
        "price_list_currency": "KRW",
        "plc_conversion_rate": 1.0,
        "ignore_pricing_rule": 0,
        "update_stock": 0,
        "total_qty": 1.0,
        "total_net_weight": 0.0,
        "base_total": 1000000.0,
        "base_net_total": 1000000.0,
        "total": 1000000.0,
        "net_total": 1000000.0,
        "tax_category": "",
        "base_total_taxes_and_charges": 0.0,
        "total_taxes_and_charges": 0.0,
        "base_grand_total": 1000000.0,
        "base_rounding_adjustment": 0.0,
        "base_rounded_total": 1000000.0,
        "base_in_words": "KRW One Million only.",
        "grand_total": 1000000.0,
        "rounding_adjustment": 0.0,
        "use_company_roundoff_cost_center": 0,
        "rounded_total": 1000000.0,
        "in_words": "KRW One Million only.",
        "total_advance": 0.0,
        "outstanding_amount": 1000000.0,
        "disable_rounded_total": 0,
        "apply_discount_on": "Grand Total",
        "base_discount_amount": 0.0,
        "is_cash_or_non_trade_discount": 0,
        "additional_discount_percentage": 0.0,
        "discount_amount": 0.0,
        "other_charges_calculation": "<div class=\"tax-break-up\" style=\"overflow-x: auto;\">\n\t<table class=\"table table-bordered table-hover\">\n\t\t<thead>\n\t\t\t<tr>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<th class=\"text-left\">Item</th>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<th class=\"text-right\">Taxable Amount</th>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<th class=\"text-right\">Marketing Expenses</th>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</thead>\n\t\t<tbody>\n\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td>testItem</td>\n\t\t\t\t\t<td class=\"text-right\">\n\t\t\t\t\t\t\n\t\t\t\t\t\t\tKRW 1,000,000.00\n\t\t\t\t\t\t\n\t\t\t\t\t</td>\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t<td class=\"text-right\">\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(0.0%)\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tKRW 0.00\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\n\t\t</tbody>\n\t</table>\n</div>",
        "total_billing_hours": 0.0,
        "total_billing_amount": 0.0,
        "base_paid_amount": 0.0,
        "paid_amount": 0.0,
        "base_change_amount": 0.0,
        "change_amount": 0.0,
        "allocate_advances_automatically": 0,
        "only_include_allocated_payments": 0,
        "write_off_amount": 0.0,
        "base_write_off_amount": 0.0,
        "write_off_outstanding_amount_automatically": 0,
        "redeem_loyalty_points": 0,
        "loyalty_points": 0,
        "loyalty_amount": 0.0,
        "territory": "Korea, Republic of",
        "ignore_default_payment_terms_template": 0,
        "po_no": "",
        "debit_to": "Debtors - T",
        "party_account_currency": "KRW",
        "is_opening": "No",
        "against_income_account": "Sales - T",
        "amount_eligible_for_commission": 0.0,
        "commission_rate": 0.0,
        "total_commission": 0.0,
        "group_same_items": 0,
        "language": "en",
        "status": "Draft",
        "customer_group": "Individual",
        "is_internal_customer": 0,
        "is_discounted": 0,
        "remarks": "No Remarks",
        "repost_required": 0,
        "doctype": "Sales Invoice",
        "items": [
            {
                "name": "ea23a83940",
                "owner": "Administrator",
                "creation": "2024-01-23 06:39:11.460831",
                "modified": "2024-01-23 06:39:11.460831",
                "modified_by": "Administrator",
                "docstatus": 0,
                "idx": 1,
                "has_item_scanned": 0,
                "item_name": "testItem",
                "description": "<div class=\"ql-editor read-mode\"><p>djkajsdlfjklsdafjk</p></div>",
                "qty": 1.0,
                "stock_uom": "Nos",
                "uom": "Barleycorn",
                "conversion_factor": 3040.0,
                "stock_qty": 3040.0,
                "price_list_rate": 0.0,
                "base_price_list_rate": 0.0,
                "margin_type": "",
                "margin_rate_or_amount": 0.0,
                "rate_with_margin": 0.0,
                "discount_percentage": 0.0,
                "discount_amount": 0.0,
                "base_rate_with_margin": 0.0,
                "rate": 1000000.0,
                "amount": 1000000.0,
                "base_rate": 1000000.0,
                "base_amount": 1000000.0,
                "pricing_rules": "",
                "stock_uom_rate": 328.947368421,
                "is_free_item": 0,
                "grant_commission": 0,
                "net_rate": 1000000.0,
                "net_amount": 1000000.0,
                "base_net_rate": 1000000.0,
                "base_net_amount": 1000000.0,
                "delivered_by_supplier": 0,
                "income_account": "Sales - T",
                "is_fixed_asset": 0,
                "enable_deferred_revenue": 0,
                "weight_per_unit": 0.0,
                "total_weight": 0.0,
                "incoming_rate": 0.0,
                "allow_zero_valuation_rate": 0,
                "actual_batch_qty": 0.0,
                "actual_qty": 0.0,
                "delivered_qty": 0.0,
                "cost_center": "Main - T",
                "page_break": 0,
                "parent": "ACC-SINV-RET-2024-00001",
                "parentfield": "items",
                "parenttype": "Sales Invoice",
                "doctype": "Sales Invoice Item"
            }
        ],
        "payments": [],
        "pricing_rules": [],
        "packed_items": [],
        "payment_schedule": [
            {
                "name": "836e8f56c9",
                "creation": "2024-01-23 06:39:12.508521",
                "modified": "2024-01-23 06:39:12.508521",
                "modified_by": "Administrator",
                "docstatus": 0,
                "idx": 1,
                "due_date": "2024-01-23",
                "invoice_portion": 100.0,
                "discount": 0.0,
                "payment_amount": 1000000.0,
                "outstanding": 1000000.0,
                "paid_amount": 0.0,
                "discounted_amount": 0.0,
                "base_payment_amount": 1000000.0,
                "parent": "ACC-SINV-RET-2024-00001",
                "parentfield": "payment_schedule",
                "parenttype": "Sales Invoice",
                "doctype": "Payment Schedule"
            }
        ],
        "taxes": [
            {
                "name": "4e3ef8da43",
                "owner": "Administrator",
                "creation": "2024-01-23 06:39:11.460831",
                "modified": "2024-01-23 06:39:11.460831",
                "modified_by": "Administrator",
                "docstatus": 0,
                "idx": 1,
                "charge_type": "Actual",
                "account_head": "Marketing Expenses - T",
                "description": "Marketing Expenses",
                "included_in_print_rate": 0,
                "included_in_paid_amount": 0,
                "cost_center": "Main - T",
                "rate": 0.0,
                "account_currency": "KRW",
                "tax_amount": 0.0,
                "total": 1000000.0,
                "tax_amount_after_discount_amount": 0.0,
                "base_tax_amount": 0.0,
                "base_total": 1000000.0,
                "base_tax_amount_after_discount_amount": 0.0,
                "item_wise_tax_detail": "{\"testItem\":[0.0,0.0]}",
                "dont_recompute_tax": 0,
                "parent": "ACC-SINV-RET-2024-00001",
                "parentfield": "taxes",
                "parenttype": "Sales Invoice",
                "doctype": "Sales Taxes and Charges"
            }
        ],
        "timesheets": [],
        "advances": [],
        "sales_team": []
    }
}